### ISSUE TITLE
School's quest wording and suggestions.

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#121]
* **Modpack Version**: FTB Academy BETA 7

Below you can find a list of changes suggestions and issues I've found throughout the School's quests.
 
Comments below will be based on the information provided in the quests and not the Guide.
SUGGESTION: Additionally, I don't know about you guys but the thing I hated about school was "way too many things to read and not enough things to figure out on my own".

Add a note on the wall in the starting area that states: 
"**Press "T" and type /reset_school to restart the school.**"

INFO: Tutorial needs a page about *"That box in the top-middle of the screen" (The One Probe)*.

# School quests:
#### In the tutorial - page 1/10

"To open them, click the button ~~at~~ **in** the top left..."

#### Item and Recipe Searching

I guess this will apply to all the other quests too, but the first time shortcut keys are mentioned (in this case **R** and **U**), there should be a note that these can be changed in "Controls" menu.

#### Introduction to Storage

There's a lot of mods that allow you to store items easier **than in the default (vanilla Minecraft) Chests**.

#### Digital Storage

*Inconsistency in Storage Room*
There is no message that there are quests to be completed in this room, but only notifications (quest complete messages) when player does what the "message on the wall" states. Possibly adding a message on entry to open Quests could help (but not saying how to do that, to test their knowledge from the Tutorial)?

If by chance a player figures out that there are some quests to be completed, the next quest after Bulk Drawers suggest to "Look at Refined Storage". But nothing happens when done so (at least in the way it did in Bulk Drawers quest just moments ago).
Message should state that the player should access the inventory of each RS block by right clicking it (or something along those lines). 

Refined Storage section should sit where Black Hole Tank and Portable Tank currently are to keep the flow of the quest consistent with the room layout.

#### Fluid Storage

Having a message after the paragraph "Blocks that store fluids..." reminding you (or explaining to those players that did not read the Guide) that you can search for anything (including) "Tank" in JEI could be helpful to reinforce the knowledge gained in JEI quest.

*Unless I've missed it, there is no message to head to "Technology & Automation" room unless player opens quest. At this stage I would remind a player (again) to do that.*

#### Filtering

BUG: Messages on the wall overlap:
[Screenshot](http://mrgreghimself.com/ftb_academy/Sorting.png)

#### Making Energy

Last paragraph needs an explanation that placing Coal Generator on Iron Block is not a requirement in the game itself (just this quest). Additionally it might be worth adding something similar to words below, before telling a player to add Coal:
*"Just like with items in the Storage Room, you can right click on many modded blocks/machines to open their inventory. Add Coal to Coal Generator's Inventory".*

#### Moving Energy

Same as above with regards to the Wool not being a requirement to place ducts in the game itself.

#### Using Energy

Amend last paragraph:
"Place Redstone Furnace on the Block of Lapis Lazuli and use it **(right click)** to smelt some Pulverized Iron **into Iron Ingots**. Than take the Ingots out to complete the quest."

#### Storing Energy

Amend second paragraph:
"Use the Crescent Hammer you got from the ~~Automation~~ **Filtering** quest(~~s~~) and sneak right click it ~~on~~ **in** the middle **of the** Fluxduct to break it, ~~and~~ then place the Energy Cell in it's place.

BUG: After removing Energy Cell with Crescent Hammer I can't place it back again.

#### Using Upgraded Machines
After completing the quest, player is not being told to leave the area and head to the next room. Not required but helpful in case Quests are not opened.

SUGGESTION:
Would it be possible to introduce JourneyMap mod by having pre-added (if possible) Waypoints to each of the rooms? This would allow people to get used to follow the beams.

Speaking of JourneyMap mod:
Does it generate a new school each time you reset? I've noticed that JourneyMap mod displays 4 Schools for me at this current time.

#### Using Starlight

The quest asks you to craft a Resonating Wand, but what it doesn't quite explain is how "near" the Crystal the Crafting Table needs to be. Might be worth adding that player needs to place the Crafting Table on one of the Blocks of Quartz near the Crystal and adding to that, that item tool tips for each block/item can give you important information or stats of the item just like a Crafting Table in this example.

INFO: Again it might be worth telling the player in the last quest to head to the next area when the quest is completed (in case they didn't open the quest or didn't hover over the quest task).

#### Generating Mana
"... Fill it with Water **using** ~~with~~ **a** ~~the~~ Water Bucket, make and then throw in the petals..."  
INFO: *Mention that the pcolours of petals important when crafting certain items in Botania*

Swap 2nd and 3rd paragraph to tell the player what to do with the petals before explaining what the Endoflame is for.

And finally amend the last paragraph:
"Once you've made the Endoflame, place it on the lightest Grass Block **and generate some Mana as explained above**."

# THE END

Please ping me if anything.

**Comment by aaronhowser1** [comment]
Add a note on the wall in the starting area that states: 
"**Press "T" and type /reset_school to restart the school.**" @Sunekaer

INFO: Tutorial needs a page about *"That box in the top-middle of the screen" (The One Probe)*.


# School quests:
#### In the tutorial - page 1/10

"To open them, click the button ~~at~~ **in** the top left..."
**Done**

#### Item and Recipe Searching

I guess this will apply to all the other quests too, but the first time shortcut keys are mentioned (in this case **R** and **U**), there should be a note that these can be changed in "Controls" menu.
![image](https://user-images.githubusercontent.com/15698722/62169699-87b11200-b2ee-11e9-9296-b660c26e6a6a.png)


#### Introduction to Storage

There's a lot of mods that allow you to store items easier **than in the default (vanilla Minecraft) Chests**.
**Changed to "easily"**

#### Digital Storage

*Inconsistency in Storage Room*
There is no message that there are quests to be completed in this room, but only notifications (quest complete messages) when player does what the "message on the wall" states. Possibly adding a message on entry to open Quests could help (but not saying how to do that, to test their knowledge from the Tutorial)? 
**We added something like this to the magic area, but we can move it to be earlier. @Sunekaer?**

If by chance a player figures out that there are some quests to be completed, the next quest after Bulk Drawers suggest to "Look at Refined Storage". But nothing happens when done so (at least in the way it did in Bulk Drawers quest just moments ago).
Message should state that the player should access the inventory of each RS block by right clicking it (or something along those lines). 

Refined Storage section should sit where Black Hole Tank and Portable Tank currently are to keep the flow of the quest consistent with the room layout.


#### Fluid Storage

Having a message after the paragraph "Blocks that store fluids..." reminding you (or explaining to those players that did not read the Guide) that you can search for anything (including) "Tank" in JEI could be helpful to reinforce the knowledge gained in JEI quest.
![image](https://user-images.githubusercontent.com/15698722/62169839-1756c080-b2ef-11e9-8a95-afe3d3618407.png)


*Unless I've missed it, there is no message to head to "Technology & Automation" room unless player opens quest. At this stage I would remind a player (again) to do that.*
**We're going to have horizontal banners on the ground with arrows to point you towards the next room**

#### Filtering

BUG: Messages on the wall overlap:
[Screenshot](http://mrgreghimself.com/ftb_academy/Sorting.png)
 @Sunekaer 

#### Making Energy

Last paragraph needs an explanation that placing Coal Generator on Iron Block is not a requirement in the game itself (just this quest). Additionally it might be worth adding something similar to words below, before telling a player to add Coal:
*"Just like with items in the Storage Room, you can right click on many modded blocks/machines to open their inventory. Add Coal to Coal Generator's Inventory".*
**I don't think this is necessary**

#### Moving Energy

Same as above with regards to the Wool not being a requirement to place ducts in the game itself.

#### Using Energy

Amend last paragraph:
"Place Redstone Furnace on the Block of Lapis Lazuli and use it **(right click)** to smelt some Pulverized Iron **into Iron Ingots**. Than take the Ingots out to complete the quest."

#### Storing Energy

Amend second paragraph:
"Use the Crescent Hammer you got from the ~~Automation~~ **Filtering** quest(~~s~~) and sneak right click it ~~on~~ **in** the middle **of the** Fluxduct to break it, ~~and~~ then place the Energy Cell in it's place.
**Changed Automation to Filtering, not going to change the rest because "in" doesn't work I think and "and then" flows better than "then"**

BUG: After removing Energy Cell with Crescent Hammer I can't place it back again.
@Sunekaer **maybe have a hidden quest that unlocks after placing the Energy Cell, and then if it detects the Energy Cell it consumes it and rewards you with the same unplacable one?**

#### Using Upgraded Machines
After completing the quest, player is not being told to leave the area and head to the next room. Not required but helpful in case Quests are not opened.
**Arrows on ground will help here**

SUGGESTION:
Would it be possible to introduce JourneyMap mod by having pre-added (if possible) Waypoints to each of the rooms? This would allow people to get used to follow the beams.
**Not possible, because the island is precedurally generated (for servers) instead of being part of the world save**

Speaking of JourneyMap mod:
Does it generate a new school each time you reset? I've noticed that JourneyMap mod displays 4 Schools for me at this current time.
**Yes**

#### Using Starlight

The quest asks you to craft a Resonating Wand, but what it doesn't quite explain is how "near" the Crystal the Crafting Table needs to be. Might be worth adding that player needs to place the Crafting Table on one of the Blocks of Quartz near the Crystal and adding to that, that item tool tips for each block/item can give you important information or stats of the item just like a Crafting Table in this example.
**The Floating Crystal has a rediculously large range, and they're only found in small rooms during play.**
![image](https://user-images.githubusercontent.com/15698722/62170128-f6429f80-b2ef-11e9-823e-43000d5f65f6.png)
**Apparently I had started writing this out already but forgot half-way through lol**
![image](https://user-images.githubusercontent.com/15698722/62170237-5df8ea80-b2f0-11e9-9e5e-c09b8d3122b4.png)
**(We changed it to Wool)**

INFO: Again it might be worth telling the player in the last quest to head to the next area when the quest is completed (in case they didn't open the quest or didn't hover over the quest task).


#### Generating Mana
"... Fill it with Water **using** ~~with~~ **a** ~~the~~ Water Bucket, make and then throw in the petals..."  
Swap 2nd and 3rd paragraph to tell the player what to do with the petals before explaining what the Endoflame is for.
And finally amend the last paragraph:
"Once you've made the Endoflame, place it on the lightest Grass Block **and generate some Mana as explained above**."
![image](https://user-images.githubusercontent.com/15698722/62170424-f8592e00-b2f0-11e9-9f81-5c359ca919e6.png)

**We also have this new banner**
![image](https://user-images.githubusercontent.com/15698722/62170379-d069ca80-b2f0-11e9-8b4c-bc44e55a64db.png)

INFO: *Mention that the pcolours of petals important when crafting certain items in Botania*
**I don't think this is necessary, the recipe specifies that color so it should be obvious that that color is needed**

**Comment by MrGREGhimself** [comment]
> Changed Automation to Filtering, not going to change the rest because "in" doesn't work I think and "and then" flows better than "then"

"and then" I can deal with but without coma just before "and" :) but rules of English prepositions will not agree with "on".
Reference: [Middle](https://dictionary.cambridge.org/dictionary/english/middle)

If you insist on having "on" in there, I suggest the following instead:
> "Use the Crescent Hammer you got from the Filtering quest and sneak right-click **on** it **in** the middle of the Fluxduct to break it and then place the Energy Cell in its place."

With regards to recipe for the Endoflame:
My first experience with Botania was exactly that: Wool is Wool (regardless of colour - in vanilla) so Petal must be Petal and how wrong was I :)
The above is correct but not for everything so adding information about colours could teach people to pay more attention to what is being displayed in JEI.

**Comment by aaronhowser1** [comment]
My thoughts on "on" are that you're clicking on the block. The block you're clicking on is the middle Fluxduct. You aren't clicking in the block, you're clicking on it (as evidenced by Grammarly yelling at me here)
![image](https://user-images.githubusercontent.com/15698722/62171700-7a4b5600-b2f5-11e9-92b6-7d80e1ed1f0d.png)

**Comment by MrGREGhimself** [comment]
That being the case all it needs is the word "block" after "Fluxducts". :)

**Comment by aaronhowser1** [comment]
I agree with that, changed

**Comment by aaronhowser1** [comment]
Add a note on the wall in the starting area that states:
"Press "T" and type /reset_school to restart the school."

This already exists, doesn't it? Or is that a Beta 8 thing?
![image](https://user-images.githubusercontent.com/15698722/62279973-adced300-b410-11e9-8515-5a7f74301330.png)

**Comment by MrGREGhimself** [comment]
It was more about adding "press T" part. Command itself does sit on the wall in beta 7.

**Comment by Sunekaer** [comment]
Won’t be doing command block, that would cause issues on server as that isn’t a thing there is enable by default, and it a player sees a sign and a button they’ll click the button before they’ll read the sign and some will same click it’s and cause lag. Therefor it will be a command, and we maybe can have lat add them as buttons in like ftbu and @aaronhowser1 explain those button are there in the start tutorial ?

**Comment by aaronhowser1** [comment]
If anything hasn't been addressed here or in another issue, please make new issues for them
