### ISSUE TITLE
Getting Started quest page amendments, suggestions and bugs.

### ISSUE THREAD

**Issue by MrGREGhimself** [Sunekaer/academy-testing#126]
* **Modpack Version**: FTB Academy BETA7

# Getting Started Quest Page

#### Agricultural Revolution

BUG: Quest suggests to "plant some crops". In my case planting a carrot didn't complete the quest.
SUGGESTION: As the quest is about planting (and it requires seeds to complete) it might be worth changing Task's icon from "Wheat" to "Seeds" especially that the next quest (breeding one) has got the same Task icon.

#### Packback

When hovering over the task icon what you see is this:
Screenshot: [Packback](http://mrgreghimself.com/ftb_academy/Packback.png)

SUGGESTION: Can this be changed from "academy.simplybackpacks.task" to "Any Backpack" instead?
Also at this stage in the game new players will not know what or where a Bauble slot is especially if those slots are toggled OFF by default.

#### Lookin' Good

I suggest changing the text to:
> "... Craft a Chisel, open its menu and insert a block into it to see ..."

Yep, just a coma instead of "and". Maybe providing an example of the block could help. Ie. "Like stone or dirt".

#### ""Small""

Quest title has got 2 sets of quotation marks.

I suggest changing the text to:
> ... its contents when destroyed **and** the Keeper **will** be removed. 

BUG: Completing this quest showed 2 messages about completing it as there is a duplicate quest in the "Basic Storage" section.

#### Better Building

Text to be changed to:
> .. Hold one in your hand, look at a block and you can right-click to place that ...

Just coma instead of another "and".

#### Location, Location, Location

Text to:
> Finding a nice spot to settle down ~~in~~ is one of the most important part**s** of building a base.

Most people would not use "in" in this case and the word "part" needs "s" at the end.

#### Like an Eagle Piloting a Blimp

Text to:
> You will bounce **upon falling** ~~after falls~~ when wearing Slime Boots, negating all fall damage.

In the above, I would use a single instance of falling.

Add at the end of the description:
> You can sneak to prevent yourself from bouncing **but you might take some fall damage**.

#### Hot Stuff

Text to:
> The Smeltery allows you to melt metals in order to make metal tool parts **, blocks, ingots and items**.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/62195164-059e0900-b341-11e9-8fa5-044246765f42.png)
The backpack task has a working name for me, although that might have been a bug that was fixed since beta 7 was released

**Comment by aaronhowser1** [comment]
* **Modpack Version**: FTB Academy BETA7

# Getting Started Quest Page

#### Agricultural Revolution

BUG: Quest suggests to "plant some crops". In my case planting a carrot didn't complete the quest.
SUGGESTION: As the quest is about planting (and it requires seeds to complete) it might be worth changing Task's icon from "Wheat" to "Seeds" especially that the next quest (breeding one) has got the same Task icon.
**Changed it to "Harvest crops" because it's an advancement task and the advancement gets set off when you harvest a crop**

#### Packback

When hovering over the task icon what you see is this:
Screenshot: [Packback](http://mrgreghimself.com/ftb_academy/Packback.png)
**Fixed**

SUGGESTION: Can this be changed from "academy.simplybackpacks.task" to "Any Backpack" instead?
Also at this stage in the game new players will not know what or where a Bauble slot is especially if those slots are toggled OFF by default.
**Fixed broken lang key, mentioned how to access bauble slots**

#### Lookin' Good

I suggest changing the text to:
> "... Craft a Chisel, open its menu and insert a block into it to see ..."

Yep, just a coma instead of "and". Maybe providing an example of the block could help. Ie. "Like stone or dirt".
**Done**

#### ""Small""

Quest title has got 2 sets of quotation marks.
**This is on purpose, because the tooltip says `"Small"`. It's supposed to be funny, but 🤷‍♂️**

I suggest changing the text to:
> ... its contents when destroyed **and** the Keeper **will** be removed. 

**I'd rather keep it as it is now**

BUG: Completing this quest showed 2 messages about completing it as there is a duplicate quest in the "Basic Storage" section.
**Duplicate removed**

#### Better Building

Text to be changed to:
> .. Hold one in your hand, look at a block and you can right-click to place that ...
Just coma instead of another "and".

**Done**

#### Location, Location, Location

Text to:
> Finding a nice spot to settle down ~~in~~ is one of the most important part**s** of building a base.

Most people would not use "in" in this case and the word "part" needs "s" at the end.
**Done**

#### Like an Eagle Piloting a Blimp

Text to:
> You will bounce **upon falling** ~~after falls~~ when wearing Slime Boots, negating all fall damage.

In the above, I would use a single instance of falling.
**"You will bounce when landing while wearing Slime Boots,"**

Add at the end of the description:
> You can sneak to prevent yourself from bouncing **but you might take some fall damage**.

**"You can sneak to prevent yourself from bouncing, although you will get fall damage as normal."**

#### Hot Stuff

Text to:
> The Smeltery allows you to melt metals in order to make metal tool parts **, blocks, ingots and items**.
**Done**
