### ISSUE TITLE
teams and rewards dupes?

### ISSUE THREAD

**Issue by deividaslord** [Sunekaer/academy-testing#139]
I left my team, joined suggested team 1player. And i could get rewards again. Which means, you could keep on receiving rewards again and again. You just need to complete one starter quest, by taking a bucket with water.

**Comment by deividaslord** [comment]
Sorry, some rewards this time.. And my whole inventory got whiped

**Comment by deividaslord** [comment]
i guess you did it because you leave "school"

**Comment by deividaslord** [comment]
Allthough maybe it is a bug idk, but you lose items in your inv and can reclaim rewards. Same as you leave and join friends team..

**Comment by Sunekaer** [comment]
Okay dont care about the rewards unless they are from school.
Fixed so the clearing inv shouldnt happen again.

**Comment by aaronhowser1** [comment]
To expand, everything in the school is now a team reward. That means if anyone from the team claims it, nobody else can. We don't have any other rewards as team rewards because we like everyone being able to claim their own reward from a quest, like everyone gets a stack of torches or whatever. The dupe bug is a thing with FTB Utilities / Quests, if you join a team you get to claim non-team rewards that they've unlocked, even if you've already claimed that reward in a different team. There's not really much we can do there.
